lib/photography_web/router.ex
defmodule PhotographyWeb.Router do
  use PhotographyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PhotographyWeb.Auth

  end

  pipeline :backend_layout do
    plug :put_layout, {PhotographyWeb.LayoutView, :backend}
  end

#  pipeline :api do
#    plug :accepts, ["json"]
#  end


  scope "/photos/", PhotographyWeb do
    pipe_through :browser

    get "/", PhotoController, :index
    get "/:photo_slug", PhotoController, :show

    scope "/admin", Admin, as: :admin do
      pipe_through [:backend_layout]

      get "/login", AdminController, :login
      post "/logged-in", AdminController, :logged_in
      delete "/logout", AdminController, :logout

      resources "/photos", PhotoController
      get "/photos/:id/edit-picture", PhotoController, :edit_picture

    end
  end

end

lib/photography_web/views/layout_view.ex
defmodule PhotographyWeb.LayoutView do
  use PhotographyWeb, :view
end

lib/photography_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Photography</title>


    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#000000">
    <meta name="msapplication-TileColor" content="#f9f8cc">
    <meta name="theme-color" content="#f9f8cc">

    <meta name="turbolinks-cache-control" content="no-cache">


    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed:300|Fira+Sans:500&display=swap" rel="stylesheet">
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>" defer></script>

  </head>
  <body>
    <header>
      <section class="container header-container">
      <svg viewBox="0 0 224 226" xmlns="http://www.w3.org/2000/svg" class="logo">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M127 0H123V31.8718C119.083 31.2975 115.076 31 111 31C74.0627 31 42.8298 55.4223 32.5678 89H0V93H31.4561H35H35.5875C44.419 59.6121 74.8351 35 111 35C154.078 35 189 69.9218 189 113C189 152.69 159.355 185.456 121 190.365V194.396C121 194.396 121 194.396 121 194.396V226H125V193.81C163.618 187.166 193 153.514 193 113C193 105.379 191.96 98.0011 190.015 91H224V87H189V87.631C179.922 59.7005 156.259 38.3474 127 32.5602V0ZM115 69H106V158H115V69Z"/>
      </svg>
        <nav>
            <%= if @current_user do %>
            <%= active_link(@conn, "Admin", to: Routes.admin_photo_path(@conn, :index), active: :inclusive, class: "nav-link")%>
            <%= link "Log out", to: Routes.admin_admin_path(@conn, :logout), method: "delete" , class: "nav-link"%>
            <% end %>
        </nav>
      </section>
    </header>
    <main class="container text-container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
        <footer>
        <div class="legal">
                   <a href="https://1aus2.de/impressum">Impressum</a>
                   <a href="https://1aus2.de/datenschutz">Datenschutz</a>
                </div>
        <a href="mailto:kontakt@joshuastuebner.com">kontakt[at]joshuastuebner.com</a>

        </footer>
  </body>
</html>

lib/photography_web/templates/layout/backend.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Photography</title>



<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#000000">
<meta name="msapplication-TileColor" content="#f9f8cc">
<meta name="theme-color" content="#f9f8cc">
    <meta name="turbolinks-cache-control" content="no-cache">




    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed:300|Fira+Sans:500&display=swap" rel="stylesheet">
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>" defer></script>
  </head>
  <body>
<main class="container">
        <header class="small-header">
              <section class="container small-header-container">
              <svg viewBox="0 0 224 226" xmlns="http://www.w3.org/2000/svg" class="logo">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M127 0H123V31.8718C119.083 31.2975 115.076 31 111 31C74.0627 31 42.8298 55.4223 32.5678 89H0V93H31.4561H35H35.5875C44.419 59.6121 74.8351 35 111 35C154.078 35 189 69.9218 189 113C189 152.69 159.355 185.456 121 190.365V194.396C121 194.396 121 194.396 121 194.396V226H125V193.81C163.618 187.166 193 153.514 193 113C193 105.379 191.96 98.0011 190.015 91H224V87H189V87.631C179.922 59.7005 156.259 38.3474 127 32.5602V0ZM115 69H106V158H115V69Z"/>
              </svg>
                <nav>
                    <%= active_link(@conn, "Photos", to: Routes.photo_path(@conn, :index), active: :inclusive, class: "nav-link")%>

                    <%= if @current_user do %>
                    <%= active_link(@conn, "Admin", to: Routes.admin_photo_path(@conn, :index), active: :inclusive, class: "nav-link")%>
                    <%= link "Log out", to: Routes.admin_admin_path(@conn, :logout), method: "delete" , class: "nav-link"%>
                    <% end %>
                </nav>
              </section>
            </header>
      <div class="text-container">
                    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
                    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
      </div>
    </main>
    <footer>
    <div class="legal">
               <a href="https://1aus2.de/impressum">Impressum</a>
               <a href="https://1aus2.de/datenschutz">Datenschutz</a>
            </div>
        <a href="mailto:kontakt@joshuastuebner.com">kontakt[at]joshuastuebner.com</a>

    </footer>


    </body>
</html>

lib/photography_web/templates/layout/photo.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Photography</title>



<link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/apple-touch-icon.png") %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/favicon-32x32.png") %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/favicon-16x16.png") %>">
<link rel="manifest" href="<%= Routes.static_path(@conn, "/site.webmanifest") %>">
<link rel="mask-icon" href="<%= Routes.static_path(@conn, "/safari-pinned-tab.svg") %>" color="#000000">
<meta name="msapplication-TileColor" content="#f9f8cc">
<meta name="theme-color" content="#f9f8cc">
    <meta name="turbolinks-cache-control" content="no-cache">




    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed:300|Fira+Sans:500&display=swap" rel="stylesheet">
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>" defer></script>

  </head>
  <body>
    <header class="small-header">
      <section class="container small-header-container">
      <svg viewBox="0 0 224 226" xmlns="http://www.w3.org/2000/svg" class="logo">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M127 0H123V31.8718C119.083 31.2975 115.076 31 111 31C74.0627 31 42.8298 55.4223 32.5678 89H0V93H31.4561H35H35.5875C44.419 59.6121 74.8351 35 111 35C154.078 35 189 69.9218 189 113C189 152.69 159.355 185.456 121 190.365V194.396C121 194.396 121 194.396 121 194.396V226H125V193.81C163.618 187.166 193 153.514 193 113C193 105.379 191.96 98.0011 190.015 91H224V87H189V87.631C179.922 59.7005 156.259 38.3474 127 32.5602V0ZM115 69H106V158H115V69Z"/>
      </svg>
        <nav>
            <%= if @current_user do %>
            <%= active_link(@conn, "Admin", to: Routes.admin_photo_path(@conn, :index), active: :inclusive, class: "nav-link")%>
            <%= link "Log out", to: Routes.admin_admin_path(@conn, :logout), method: "delete" , class: "nav-link"%>
            <% end %>
        </nav>
      </section>
    </header>
    <main class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
        <footer>
        <div class="legal">
           <a href="https://1aus2.de/impressum">Impressum</a>
           <a href="https://1aus2.de/datenschutz">Datenschutz</a>
        </div>
                <a href="mailto:kontakt@joshuastuebner.com">kontakt[at]joshuastuebner.com</a>

        </footer>

  </body>
</html>